#!/usr/bin/env bash
#=============================================================================
# VPS Network Optimizer — 一键优化脚本
# 仓库：https://github.com/djme0/bbr-sysctl
# 用法：curl -fsSL https://raw.githubusercontent.com/djme0/bbr-sysctl/main/vps-optimizer.sh | sudo bash
#=============================================================================
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; }
section() { echo ""; echo -e "${CYAN}===== $1 =====${NC}"; }

if [[ $EUID -ne 0 ]]; then
    error "请以 root 用户运行"
    exit 1
fi

#------------ 硬件探测 ------------
ARCH=$(uname -m)
case $ARCH in
    x86_64|amd64)  ARCH_TYPE="x86_64" ;;
    aarch64|arm64) ARCH_TYPE="arm64"  ;;
    *)             ARCH_TYPE="other"  ;;
esac
CPU_CORES=$(nproc)
MEM_TOTAL_MB=$(grep MemTotal /proc/meminfo | awk '{print int($2/1024)}')
DISK_FREE_GB=$(df -BG / | awk 'NR==2 {print int($4)}')
IFACE=$(ip route get 1 2>/dev/null | awk '{print $5; exit}')
[[ -z "$IFACE" ]] && IFACE="eth0"
AVAILABLE_CC=$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null)

info "架构: ${ARCH_TYPE} | 核心: ${CPU_CORES} | 内存: ${MEM_TOTAL_MB}MB | 磁盘剩余: ${DISK_FREE_GB}G | 网卡: ${IFACE}"

#------------ 虚拟内存 ------------
SWAP_FILE="/swapfile"
setup_swap() {
    local current_swap=$(free -m | awk '/Swap:/ {print $2}')
    local swap_size
    if   [[ $MEM_TOTAL_MB -le 1024 ]]; then swap_size=2048
    elif [[ $MEM_TOTAL_MB -le 2048 ]]; then swap_size=4096
    elif [[ $MEM_TOTAL_MB -le 4096 ]]; then swap_size=6144
    else swap_size=8192
    fi
    if [[ $current_swap -ge $swap_size ]]; then
        info "当前 swap 足够 (${current_swap}MB >= ${swap_size}MB)，跳过"
        return
    fi
    if [[ $DISK_FREE_GB -lt $(( (swap_size + 1023) / 1024 )) ]]; then
        swap_size=$(( DISK_FREE_GB * 1024 - 512 ))
        [[ $swap_size -le 128 ]] && { warn "磁盘空间过小，放弃 swap"; return; }
    fi
    info "创建 ${swap_size}MB swap 文件..."
    [[ -f "$SWAP_FILE" ]] && swapoff "$SWAP_FILE" && rm -f "$SWAP_FILE"
    fallocate -l ${swap_size}M "$SWAP_FILE" 2>/dev/null || dd if=/dev/zero of="$SWAP_FILE" bs=1M count=$swap_size status=none
    chmod 600 "$SWAP_FILE"
    mkswap "$SWAP_FILE" > /dev/null
    swapon "$SWAP_FILE"
    grep -q "$SWAP_FILE" /etc/fstab || echo "$SWAP_FILE none swap sw 0 0" >> /etc/fstab
    info "swap 创建完成，当前总量: $(free -m | awk '/Swap:/ {print $2}')MB"
}

#------------ 模块加载 ------------
load_modules() {
    modprobe sch_fq 2>/dev/null && info "sch_fq 已加载" || warn "sch_fq 不可用"
    if echo "$AVAILABLE_CC" | grep -qw bbrplus; then
        modprobe tcp_bbrplus 2>/dev/null && CC_ALGO="bbrplus" || { modprobe tcp_bbr; CC_ALGO="bbr"; }
    else
        modprobe tcp_bbr 2>/dev/null && CC_ALGO="bbr"
    fi
    info "选择拥塞控制: ${CC_ALGO}"
}

#------------ 生成 sysctl 配置 ------------
generate_sysctl() {
    local mem=$MEM_TOTAL_MB
    local rmem_max wmem_max tcp_rmem_min tcp_rmem_def tcp_rmem_max tcp_wmem_min tcp_wmem_def tcp_wmem_max
    local tcp_mem_min tcp_mem_pres tcp_mem_max file_max somaxconn backlog syn_backlog tw_buckets max_orphans limit_output notsent_lowat

    if   [[ $mem -le 1024 ]]; then
        rmem_max=16777216; wmem_max=16777216
        tcp_rmem="4096 131072 16777216"; tcp_wmem="4096 65536 16777216"
        tcp_mem="32768 65536 131072"; file_max=65536; somaxconn=32768; backlog=16384; syn_backlog=16384
        tw_buckets=8192; max_orphans=32768; limit_output=262144; notsent_lowat=32768
    elif [[ $mem -le 4096 ]]; then
        rmem_max=67108864; wmem_max=67108864
        tcp_rmem="4096 262144 67108864"; tcp_wmem="4096 131072 67108864"
        tcp_mem="131072 262144 524288"; file_max=1000000; somaxconn=65535; backlog=65535; syn_backlog=65535
        tw_buckets=16384; max_orphans=65536; limit_output=0; notsent_lowat=131072
    else
        rmem_max=134217728; wmem_max=134217728
        tcp_rmem="4096 131072 134217728"; tcp_wmem="4096 65536 134217728"
        tcp_mem="524288 786432 1048576"; file_max=2000000; somaxconn=65535; backlog=262144; syn_backlog=131072
        tw_buckets=32768; max_orphans=131072; limit_output=0; notsent_lowat=131072
    fi

    local bak="/etc/sysctl.conf.bak.$(date +%Y%m%d%H%M%S)"
    cp /etc/sysctl.conf "$bak" 2>/dev/null && info "配置已备份至 $bak"

    cat > /etc/sysctl.conf << EOF
# Generated by VPS Optimizer (https://github.com/djme0/bbr-sysctl)
# Time: $(date) / Arch: ${ARCH_TYPE} / Cores: ${CPU_CORES} / Mem: ${MEM_TOTAL_MB}MB
# Backup: $bak

fs.file-max = ${file_max}
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = ${CC_ALGO}
net.ipv4.tcp_ecn = 0

net.core.rmem_max = ${rmem_max}
net.core.wmem_max = ${wmem_max}
net.ipv4.tcp_rmem = ${tcp_rmem}
net.ipv4.tcp_wmem = ${tcp_wmem}
net.ipv4.tcp_mem = ${tcp_mem}

net.ipv4.tcp_limit_output_bytes = ${limit_output}
net.ipv4.tcp_notsent_lowat = ${notsent_lowat}

net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_adv_win_scale = 1
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_mtu_probing = 1

net.ipv4.tcp_sack = 1
net.ipv4.tcp_dsack = 1
net.ipv4.tcp_fack = 1
net.ipv4.tcp_reordering = 3
net.ipv4.tcp_early_retrans = 2

net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_retries1 = 2
net.ipv4.tcp_retries2 = 5
net.ipv4.tcp_timestamps = 1

net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_max_tw_buckets = ${tw_buckets}
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_max_orphans = ${max_orphans}

net.core.somaxconn = ${somaxconn}
net.core.netdev_max_backlog = ${backlog}
net.ipv4.tcp_max_syn_backlog = ${syn_backlog}

net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_abort_on_overflow = 0
net.ipv4.ip_forward = 1
net.ipv4.tcp_moderate_rcvbuf = 1

vm.swappiness = 10
vm.vfs_cache_pressure = 50
EOF
}

#------------ 应用配置 ------------
apply_config() {
    sysctl -p /etc/sysctl.conf > /dev/null 2>&1 || warn "部分参数可能受限，可忽略"
    tc qdisc replace dev "$IFACE" root fq 2>/dev/null && info "网卡 ${IFACE} 队列设为 fq" || warn "fq 队列设置失败"
    ip link set dev "$IFACE" txqueuelen 10000 2>/dev/null
}

#------------ 主流程 ------------
main() {
    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║       VPS Network Optimizer v2.0              ║${NC}"
    echo -e "${CYAN}║       硬核优化 · 自动识别 · 抢带宽             ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
    echo ""
    setup_swap
    load_modules
    generate_sysctl
    apply_config
    info "优化完成！建议重启你的代理服务。"
    info "回滚命令: cp /etc/sysctl.conf.bak.* /etc/sysctl.conf && sysctl -p"
}

main
